name: Build iOS App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: List project contents
      run: |
        echo "=== Project Structure ==="
        find . -type f -name "*.swift" | head -10
        echo "=== Xcode Project ==="
        ls -la *.xcodeproj/
        echo "=== TaskLock Directory ==="
        ls -la TaskLock/
        echo "=== Sources Directory ==="
        ls -la TaskLock/Sources/ || echo "Sources directory not found"
        
    - name: Validate Xcode Project
      run: |
        echo "=== Validating Xcode Project ==="
        xcodebuild -list -project TaskLock.xcodeproj
        
    - name: Build for Simulator (Debug)
      run: |
        echo "=== Building for iOS Simulator ==="
        xcodebuild -project TaskLock.xcodeproj \
                   -scheme TaskLock \
                   -configuration Debug \
                   -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
                   -derivedDataPath ./DerivedData \
                   clean build
                   
    - name: Check build output
      run: |
        echo "=== Build Output ==="
        find ./DerivedData -name "*.app" -type d || echo "No .app files found"
        find ./DerivedData -name "*.dSYM" -type d || echo "No .dSYM files found"
        ls -la ./DerivedData/Build/Products/Debug-iphonesimulator/ || echo "Debug products directory not found"
        
    - name: Upload Build Logs
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: build-logs
        path: |
          ./DerivedData/
        retention-days: 7
