name: Build iOS App

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: List files
      run: |
        echo "Project structure:"
        ls -la
        echo "TaskLock directory:"
        ls -la TaskLock/
        
    - name: Test Xcode project
      run: |
        echo "Testing Xcode project..."
        xcodebuild -list -project TaskLock.xcodeproj
        
    - name: Build for Device
      run: |
        echo "Building for iOS Device..."
        xcodebuild -project TaskLock.xcodeproj \
                   -scheme TaskLock \
                   -configuration Release \
                   -destination 'generic/platform=iOS' \
                   clean build \
                   CODE_SIGNING_ALLOWED=NO \
                   -quiet
                   
    - name: Find built app
      run: |
        echo "Looking for built app..."
        echo "Build output structure:"
        find . -path "*/Build/Products/*" -type d || echo "No Build/Products found"
        find . -name "*.app" -type d || echo "No .app files found"
        
        if find . -name "*.app" -type d | grep -q .; then
          echo "✓ App built successfully!"
        else
          echo "✗ No app found"
          exit 1
        fi
        
    - name: Create IPA
      run: |
        echo "Creating IPA..."
        # Look for .app files in common build locations
        APP_PATH=$(find . -path "*/Build/Products/Release-iphoneos/*.app" -type d | head -1)
        if [ -z "$APP_PATH" ]; then
          APP_PATH=$(find . -name "*.app" -type d | head -1)
        fi
        
        if [ -z "$APP_PATH" ]; then
          echo "No .app file found"
          echo "Searching in common locations..."
          find . -name "*.app" -type d
          find . -path "*/Build/Products/*" -type d
          exit 1
        fi
        
        echo "Found app at: $APP_PATH"
        mkdir -p ./build
        cd "$(dirname "$APP_PATH")"
        zip -r ../../build/TaskLock.ipa "$(basename "$APP_PATH")"
        cd ../../
        
        echo "IPA created successfully!"
        ls -la ./build/
                   
    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v3
      with:
        name: TaskLock.ipa
        path: ./build/TaskLock.ipa
        retention-days: 30
        
    - name: Create GitHub Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        files: ./build/TaskLock.ipa
        tag_name: v${{ github.run_number }}
        name: TaskLock v${{ github.run_number }}
        body: |
          ## TaskLock iOS App Build
          
          This is an automated build of the TaskLock iOS app.
          
          ### Installation Instructions
          1. Download the IPA file below
          2. Install via AltStore or similar sideloading tool
          3. Trust the developer certificate in iOS Settings
          
          ### Features
          - Task management with due dates and priorities
          - Task-conditional app blocking
          - Analytics and productivity insights
          - NFC/QR emergency unlock
          
          **Note**: This app requires iOS 17+ and Family Controls capability.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
