name: Build iOS App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Show project structure
      run: |
        echo "=== Project Root ==="
        ls -la
        echo "=== TaskLock Directory ==="
        ls -la TaskLock/
        echo "=== Sources Directory ==="
        ls -la TaskLock/Sources/
        echo "=== Xcode Project ==="
        ls -la TaskLock.xcodeproj/
        
    - name: Validate Xcode Project
      run: |
        echo "=== Validating Xcode Project ==="
        xcodebuild -list -project TaskLock.xcodeproj
        
    - name: Check Swift files for syntax errors
      run: |
        echo "=== Checking Swift files ==="
        find TaskLock/Sources -name "*.swift" -exec echo "Checking: {}" \; -exec swiftc -parse {} \;
        
    - name: Build for Simulator (Debug)
      run: |
        echo "=== Building for iOS Simulator ==="
        xcodebuild -project TaskLock.xcodeproj \
                   -scheme TaskLock \
                   -configuration Debug \
                   -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
                   -derivedDataPath ./DerivedData \
                   clean build \
                   CODE_SIGNING_ALLOWED=NO
                   
    - name: Check build output
      run: |
        echo "=== Build Output ==="
        find ./DerivedData -name "*.app" -type d || echo "No .app files found"
        ls -la ./DerivedData/Build/Products/Debug-iphonesimulator/ || echo "Debug products directory not found"
        
    - name: Upload Build Artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: TaskLock-build-success
        path: |
          ./DerivedData/Build/Products/Debug-iphonesimulator/
        retention-days: 7
        
    - name: Upload Build Logs
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: build-logs-failure
        path: |
          ./DerivedData/
        retention-days: 7
