name: Build iOS App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Show project structure
      run: |
        echo "=== Project Root ==="
        ls -la
        echo "=== TaskLock Directory ==="
        ls -la TaskLock/
        echo "=== Xcode Project ==="
        ls -la TaskLock.xcodeproj/
        
    - name: Validate Xcode Project
      run: |
        echo "=== Validating Xcode Project ==="
        xcodebuild -list -project TaskLock.xcodeproj
        
    - name: Build for Simulator (Debug)
      run: |
        echo "=== Building for iOS Simulator ==="
        xcodebuild -project TaskLock.xcodeproj \
                   -scheme TaskLock \
                   -configuration Debug \
                   -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
                   -derivedDataPath ./DerivedData \
                   clean build \
                   CODE_SIGNING_ALLOWED=NO
                   
    - name: Check build output
      run: |
        echo "=== Build Output ==="
        find ./DerivedData -name "*.app" -type d || echo "No .app files found"
        ls -la ./DerivedData/Build/Products/Debug-iphonesimulator/ || echo "Debug products directory not found"
        
    - name: Create IPA
      run: |
        echo "=== Creating IPA ==="
        APP_PATH=$(find ./DerivedData -name "*.app" -type d | head -1)
        if [ -z "$APP_PATH" ]; then
          echo "No .app file found"
          exit 1
        fi
        echo "Found app at: $APP_PATH"
        
        # Create IPA
        mkdir -p ./build
        cd "$(dirname "$APP_PATH")"
        zip -r ../../build/TaskLock.ipa "$(basename "$APP_PATH")"
        cd ../../
        
        echo "Created IPA at: ./build/TaskLock.ipa"
        ls -la ./build/
                   
    - name: Upload IPA
      uses: actions/upload-artifact@v3
      with:
        name: TaskLock.ipa
        path: ./build/TaskLock.ipa
        retention-days: 30
        
    - name: Upload to GitHub Releases
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        files: ./build/TaskLock.ipa
        tag_name: v${{ github.run_number }}
        name: TaskLock v${{ github.run_number }}
        body: |
          ## TaskLock iOS App Build
          
          This is an automated build of the TaskLock iOS app.
          
          ### Installation Instructions
          1. Download the IPA file
          2. Install via AltStore or similar sideloading tool
          3. Trust the developer certificate in iOS Settings
          
          ### Features
          - Task management with due dates and priorities
          - Task-conditional app blocking
          - Analytics and productivity insights
          - NFC/QR emergency unlock
          
          **Note**: This app requires iOS 17+ and Family Controls capability.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
